function [fitresult, gof] = createFit(t, v)
%CREATEFIT(T,V)
%  Create a fit.
%
%  Data for 'exponential fit' fit:
%      X Input : t
%      Y Output: v
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Apr-2014 13:24:15


%% Fit: 'exponential fit'.
[xData, yData] = prepareCurveData( t, v );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [2467.78150972986 -1.18086510896945e-06 -2402.59801538553 -1.91351235945311e-05];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'exponential fit' );
h = plot( fitresult, xData, yData );
legend( h, 'v vs. t', 'exponential fit', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'v' );
grid on


